"use client";

import { ClipboardList, CreditCard, LoaderCircle, RefreshCw, X } from "lucide-react";
import type { OrderSummary } from "@/lib/storefront/types";

type OrderPanelProps = { isLoading: boolean; startingPaymentOrderId: string | null; message: string | null; orders: OrderSummary[]; recentOrder: OrderSummary | null; paymentMessage: string | null; onClose: () => void; onRetry: () => void; onStartPayment: (orderId: string) => void; };
const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });
const dateTime = new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short" });

export function OrderPanel({ isLoading, startingPaymentOrderId, message, orders, recentOrder, paymentMessage, onClose, onRetry, onStartPayment }: OrderPanelProps) {
  const visibleOrders = recentOrder && !orders.some((order) => order.id === recentOrder.id) ? [recentOrder, ...orders] : orders;
  return <div className="fixed inset-0 z-40 flex justify-end bg-black/35" role="presentation"><aside aria-label="Orders and account" className="flex h-full w-full max-w-xl flex-col bg-[var(--surface)] shadow-xl"><header className="flex min-h-16 items-center justify-between border-b border-[var(--line)] px-5"><div className="flex items-center gap-3"><ClipboardList aria-hidden="true" size={19} /><div><h2 className="font-semibold">Orders &amp; account</h2><p className="text-xs text-[var(--muted)]">Your confirmed order history</p></div></div><button aria-label="Close orders" className="grid size-9 place-items-center border border-[var(--line)] text-[var(--muted)] hover:bg-[#f3f5f2]" onClick={onClose} type="button"><X aria-hidden="true" size={18} /></button></header>{message ? <div className="mx-5 mt-4 border-l-2 border-[var(--danger)] bg-[#fff7f6] px-3 py-2 text-sm text-[var(--danger)]" role="alert"><p>{message}</p><button className="mt-2 inline-flex h-8 items-center gap-2 border border-[var(--danger)] px-3 text-sm font-semibold hover:bg-white disabled:opacity-60" disabled={isLoading} onClick={onRetry} type="button"><RefreshCw aria-hidden="true" size={15} />Retry</button></div> : null}{paymentMessage ? <p className="mx-5 mt-4 border-l-2 border-[var(--accent)] bg-[#f4fbf6] px-3 py-2 text-sm text-[var(--accent-strong)]" role="status">{paymentMessage}</p> : null}{isLoading && visibleOrders.length > 0 ? <p aria-live="polite" className="mx-5 mt-4 flex items-center gap-2 text-sm text-[var(--muted)]"><LoaderCircle aria-hidden="true" className="animate-spin" size={16} />Refreshing order status…</p> : null}{isLoading && visibleOrders.length === 0 ? <div aria-label="Loading orders" className="grid flex-1 place-items-center text-[var(--muted)]"><LoaderCircle aria-hidden="true" className="animate-spin" size={23} /></div> : visibleOrders.length === 0 ? <div className="grid flex-1 place-items-center px-8 text-center"><div><ClipboardList aria-hidden="true" className="mx-auto text-[var(--muted)]" size={30} /><h3 className="mt-4 font-semibold">No orders yet</h3><p className="mt-2 text-sm text-[var(--muted)]">Orders you place will appear here.</p></div></div> : <ul className="flex-1 divide-y divide-[var(--line)] overflow-y-auto">{visibleOrders.map(order => <OrderRow key={order.id} onStartPayment={onStartPayment} order={order} startingPaymentOrderId={startingPaymentOrderId} />)}</ul>}</aside></div>;
}

function OrderRow({ order, startingPaymentOrderId, onStartPayment }: { order: OrderSummary; startingPaymentOrderId: string | null; onStartPayment: (orderId: string) => void }) {
  const isStartingPayment = startingPaymentOrderId === order.id;
  return <li className="px-5 py-5"><div className="flex items-start justify-between gap-4"><div><p className="font-medium">Order {shortId(order.id)}</p><p className="mt-1 text-sm text-[var(--muted)]">{formatDate(order.createdAtUtc)}</p></div><StatusBadge status={order.status} /></div><div className="mt-4 space-y-2 text-sm">{order.items.map(item => <div className="flex justify-between gap-4" key={item.id}><span className="min-w-0 text-[var(--muted)]">{item.quantity} x {item.productName}</span><span className="shrink-0">{money.format(item.totalPrice)}</span></div>)}</div>{order.shippingAddress ? <div className="mt-4 border border-[var(--line)] bg-[#fbfcfa] p-3 text-sm"><p className="font-medium">Delivery address snapshot</p><p className="mt-1 text-[var(--muted)]">{order.shippingAddress.recipientName}<br />{order.shippingAddress.line1}{order.shippingAddress.line2 ? <><br />{order.shippingAddress.line2}</> : null}<br />{order.shippingAddress.city}, {order.shippingAddress.countryCode}{order.shippingAddress.postalCode ? ` ${order.shippingAddress.postalCode}` : ""}</p></div> : null}<div className="mt-4 flex justify-between gap-4 border-t border-[var(--line)] pt-3 font-semibold"><span>Total</span><span className="text-right">{money.format(order.totalAmount)} {order.currency}</span></div>{order.status === "PendingPayment" ? <div className="mt-4 border border-[#d8d6c5] bg-[#fbfaf2] p-3"><p className="text-sm text-[var(--muted)]">No payment record has been requested for this order. Requesting processing does not confirm payment.</p><button className="mt-3 inline-flex min-h-9 items-center gap-2 bg-[var(--accent)] px-3 py-1 text-sm font-semibold text-white hover:bg-[var(--accent-strong)] disabled:cursor-not-allowed disabled:bg-[#8ba89b]" disabled={startingPaymentOrderId !== null} onClick={() => onStartPayment(order.id)} type="button">{isStartingPayment ? <LoaderCircle aria-hidden="true" className="animate-spin" size={16} /> : <CreditCard aria-hidden="true" size={16} />}{isStartingPayment ? "Requesting processing" : "Request payment processing"}</button></div> : null}</li>;
}

function StatusBadge({ status }: { status: string }) { const isPaid = status === "Paid"; const isFailed = status === "PaymentFailed" || status === "Cancelled"; const colors = isPaid ? "border-[#b9d7c6] bg-[#f4fbf6] text-[var(--accent-strong)]" : isFailed ? "border-[#f3c5c1] bg-[#fff7f6] text-[var(--danger)]" : "border-[#d8d6c5] bg-[#fbfaf2] text-[#6f6317]"; return <span className={"shrink-0 border px-2 py-1 text-xs font-medium " + colors}>{label(status)}</span>; }
function shortId(id: string) { return "#" + id.slice(0, 8).toUpperCase(); }
function label(status: string) { return status.replace(/([a-z])([A-Z])/g, "$1 $2"); }
function formatDate(value: string) { const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? "Order time unavailable" : dateTime.format(parsed); }
