ALTER TABLE Products
    ADD COLUMN IF NOT EXISTS Sku text NULL;

ALTER TABLE Products
    ADD COLUMN IF NOT EXISTS Brand text NULL;

UPDATE Products
SET Sku = CONCAT('LEGACY-', Id)
WHERE Sku IS NULL OR BTRIM(Sku) = '';

ALTER TABLE Products
    ALTER COLUMN Sku SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS UX_Products_Sku
ON Products (Sku);