{{- range $name, $app := .Values.apps }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/component: application
    {{- include "microshop.labels" $ | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
        app.kubernetes.io/component: application
        {{- include "microshop.labels" $ | nindent 8 }}
    spec:
      {{- with $.Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $name }}
          image: "{{ $.Values.global.imageRegistry }}/{{ $app.image.repository }}:{{ default $.Values.global.imageTag $app.image.tag }}"
          imagePullPolicy: {{ $.Values.global.pullPolicy }}
          resources:
            {{- toYaml (default $.Values.defaultResources $app.resources) | nindent 12 }}
          {{- if eq $app.kind "web" }}
          ports:
            - containerPort: {{ default 8080 $app.port }}
          {{- end }}
          env:
            {{- range $envName, $secretKey := $app.secretEnv }}
            - name: {{ $envName }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.secrets.name }}
                  key: {{ $secretKey }}
            {{- end }}
            {{- range $envName, $envValue := $app.env }}
            - name: {{ $envName }}
              value: {{ $envValue | quote }}
            {{- end }}
            {{- if $.Values.observability.enabled }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector:4317
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            {{- end }}
          {{- if eq $app.kind "web" }}
          readinessProbe:
            httpGet:
              path: {{ default "/health" $app.readinessPath }}
              port: {{ default 8080 $app.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: {{ default "/alive" $app.livenessPath }}
              port: {{ default 8080 $app.port }}
            initialDelaySeconds: 30
            periodSeconds: 20
          {{- end }}
{{- if eq $app.kind "web" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    {{- include "microshop.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ $name }}
  ports:
    - name: http
      port: {{ default 8080 $app.port }}
      targetPort: {{ default 8080 $app.port }}
{{- end }}
{{- end }}
